# Generated by Django 3.2.9 on 2021-11-15 14:31

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEO_Optimiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, default='', help_text='Enter the Title. Max: 60 characters', max_length=60, null=True, verbose_name='Title')),
                ('Content', models.TextField(blank=True, default='', help_text='Enter the content. Max: 165 characters', max_length=165, null=True, verbose_name='Content')),
                ('Keywords', models.TextField(blank=True, default='', help_text='Enter keywords, max 200 symbols', max_length=200, null=True, verbose_name='Keywords')),
                ('Image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='SEO/%Y/%m/%d/')),
                ('PageName', models.CharField(blank=True, default='', help_text='This field is just for a note for the admins. For which page you want to add the SEO?', max_length=55, null=True, verbose_name='Page Name')),
                ('seoid', models.IntegerField(blank=True, default=0, null=True, verbose_name='SEO id')),
            ],
            options={
                'verbose_name': 'SEO Field',
                'verbose_name_plural': 'SEO Fields',
            },
        ),
    ]
