# Generated by Django 3.2.9 on 2021-11-16 17:07

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, help_text='Enter the Title. Max: 200 characters', max_length=300, null=True)),
                ('Content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', help_text='Enter the content.', null=True, verbose_name='Content')),
                ('sortingIndex', models.IntegerField(blank=True, default=0, verbose_name='Sorting Index')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
            },
        ),
        migrations.AlterField(
            model_name='seo_optimiser',
            name='seoid',
            field=models.IntegerField(blank=True, default=0, help_text='This text is used in sourceviews.py', null=True, verbose_name='SEO id'),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, help_text='Enter the Title', max_length=100, null=True, verbose_name='Title')),
                ('Content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Введите контент', null=True, verbose_name='Content')),
                ('Image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='pages/%Y/%m/%d/')),
                ('template', models.CharField(blank=True, choices=[('about', 'home/about-us-template.html'), ('service', 'home/services-template.html')], default='about', help_text='Select a template', max_length=20, null=True, verbose_name='Template')),
                ('sortingIndex', models.IntegerField(blank=True, default=0, verbose_name='Sorting Index')),
                ('pageid', models.IntegerField(blank=True, default=0, help_text='This value is used in sourceviews.py', verbose_name='Page id')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('SEO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.seo_optimiser')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ('-Created',),
            },
        ),
    ]
