# Generated by Django 3.2.9 on 2022-02-25 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220225_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricelistCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, help_text='Введите категорию услуги', max_length=300, null=True, verbose_name='Категория услуги')),
            ],
            options={
                'verbose_name': 'Категория Прайскурант',
                'verbose_name_plural': 'Категории Прайскурантов',
            },
        ),
        migrations.CreateModel(
            name='Pricelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, help_text='Наименование прайса', max_length=300, null=True, verbose_name='Наименование услуги')),
                ('Measurement', models.CharField(blank=True, help_text='Единица', max_length=50, null=True, verbose_name='Единица')),
                ('Price', models.CharField(blank=True, help_text='Единица', max_length=50, null=True, verbose_name='Стоимость')),
                ('sortingIndex', models.IntegerField(blank=True, default=0, verbose_name='Индекс сортировки')),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.pricelistcategory')),
            ],
            options={
                'verbose_name': 'Прайскурант',
                'verbose_name_plural': 'Прайскуранты',
            },
        ),
    ]
