# Generated by Django 3.2.9 on 2022-02-28 07:45

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_pricelist_pricelistcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, help_text='Введите категорию услуги', max_length=300, null=True, verbose_name='Категория сервисов')),
            ],
            options={
                'verbose_name': 'Категория сервиса',
                'verbose_name_plural': 'Категории сервисов',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, help_text='Наименование сервиса', max_length=65, null=True, verbose_name='Длинное имя сервиса')),
                ('ShortDesc', models.TextField(blank=True, help_text='Короткое описание сервиса', max_length=165, null=True, verbose_name='Short Desciption')),
                ('Content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Короткое описание сервиса', null=True, verbose_name='Контент')),
                ('Image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='services/%Y-%m-%d/')),
                ('sortingIndex', models.IntegerField(blank=True, default=0, verbose_name='Индекс сортировки')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовать')], default='published', max_length=10)),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.servicecategory')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
            },
        ),
    ]
