# Generated by Django 3.2.9 on 2022-02-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_servicecategory_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='ShortTitle',
            field=models.CharField(blank=True, help_text='Наименование сервиса', max_length=30, null=True, verbose_name='Короткое имя сервиса'),
        ),
    ]
