# Generated by Django 3.2.9 on 2022-02-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_services_shorttitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='boxcolor',
            field=models.CharField(choices=[('dreamit-service-box-inner', 'Белый'), ('dreamit-service-box-inner1', 'Основной')], default='dreamit-service-box-inner', max_length=30, verbose_name='Цвет фона'),
        ),
    ]
