# Generated by Django 3.2.9 on 2022-02-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_services_boxcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='boxcolor',
            field=models.CharField(choices=[('0', 'Белый'), ('1', 'Основной')], default='dreamit-service-box-inner', max_length=30, verbose_name='Цвет фона'),
        ),
    ]
