# Generated by Django 3.2.9 on 2022-02-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_services_boxcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='Slug',
            field=models.CharField(blank=True, help_text='Ссылка сервиса', max_length=100, null=True, unique=True),
        ),
    ]
