# Generated by Django 3.2.9 on 2022-02-28 15:14

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_services_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, help_text='Введите категорию портфолио', max_length=300, null=True, verbose_name='Категория портфолио')),
            ],
            options={
                'verbose_name': 'Категория портфолио',
                'verbose_name_plural': 'Категории портфолио',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShortTitle', models.CharField(blank=True, help_text='Наименование портфолио', max_length=30, null=True, verbose_name='Короткое имя портфолио')),
                ('Title', models.CharField(blank=True, help_text='Наименование портфолио', max_length=65, null=True, verbose_name='Длинное имя портфолио')),
                ('Slug', models.CharField(blank=True, help_text='Ссылка портфолио', max_length=100, null=True, unique=True)),
                ('ShortDesc', models.TextField(blank=True, help_text='Короткое описание портфолио', max_length=165, null=True, verbose_name='Короткое описание')),
                ('Content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Короткое описание портфолио', null=True, verbose_name='Польное описание')),
                ('Image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='portfolio/%Y-%m-%d/')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовать')], default='published', max_length=10)),
                ('sortingIndex', models.IntegerField(blank=True, default=0, verbose_name='Индекс сортировки')),
                ('clientName', models.CharField(blank=True, help_text='Имя и фамилия клиента', max_length=50, null=True, verbose_name='Имя клиента')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.portfoliocategory')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
        ),
    ]
