# Generated by Django 3.2.9 on 2022-02-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_portfolio_portfoliocategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='Created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата окончания'),
        ),
    ]
