# Generated by Django 3.2.9 on 2022-02-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_portfolio_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliocategory',
            name='Slug',
            field=models.CharField(blank=True, help_text='Ссылка категория портфолио', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='Slug',
            field=models.CharField(blank=True, help_text='Ссылка категория услуги', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='Title',
            field=models.CharField(blank=True, help_text='Введите категорию портфолио', max_length=100, null=True, verbose_name='Категория портфолио'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='Title',
            field=models.CharField(blank=True, help_text='Введите категорию услуги', max_length=100, null=True, verbose_name='Категория сервисов'),
        ),
    ]
