# Generated by Django 3.2.9 on 2022-03-14 16:26

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20220228_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, help_text='Введите категорию ', max_length=100, null=True, verbose_name='Тип Навеса')),
                ('Slug', models.CharField(blank=True, help_text='Ссылка категория ', max_length=100, null=True, unique=True)),
                ('Content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Короткое описание ', null=True, verbose_name='Описание')),
                ('ShortDesc', models.TextField(blank=True, help_text='Короткое описание сервиса', max_length=165, null=True, verbose_name='Короткое описание')),
                ('Image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='navesy/%Y-%m-%d/')),
            ],
            options={
                'verbose_name': 'Тип навеса',
                'verbose_name_plural': 'Типы навесов',
            },
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Фото работы', 'verbose_name_plural': 'Фото работы'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Забор', 'verbose_name_plural': 'Заборы'},
        ),
        migrations.RemoveField(
            model_name='services',
            name='boxcolor',
        ),
        migrations.AddField(
            model_name='services',
            name='actualPrice',
            field=models.IntegerField(blank=True, default=0, help_text='220000', verbose_name='Обычная цена'),
        ),
        migrations.AddField(
            model_name='services',
            name='discountedPrice',
            field=models.IntegerField(blank=True, default=0, help_text='200000', verbose_name='Цена со скидкой'),
        ),
        migrations.AlterField(
            model_name='services',
            name='ShortDesc',
            field=models.TextField(blank=True, help_text='Короткое описание сервиса', max_length=165, null=True, verbose_name='Короткое описание'),
        ),
        migrations.CreateModel(
            name='Naves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShortTitle', models.CharField(blank=True, help_text='Наименование сервиса', max_length=30, null=True, verbose_name='Короткое имя сервиса')),
                ('Title', models.CharField(blank=True, help_text='Наименование сервиса', max_length=65, null=True, verbose_name='Длинное имя сервиса')),
                ('Slug', models.CharField(blank=True, help_text='Ссылка сервиса', max_length=100, null=True, unique=True)),
                ('ShortDesc', models.TextField(blank=True, help_text='Короткое описание сервиса', max_length=165, null=True, verbose_name='Короткое описание')),
                ('Content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Короткое описание сервиса', null=True, verbose_name='Контент')),
                ('Image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='navesy/%Y-%m-%d/')),
                ('actualPrice', models.IntegerField(blank=True, default=0, help_text='220000', verbose_name='Обычная цена')),
                ('discountedPrice', models.IntegerField(blank=True, default=0, help_text='200000', verbose_name='Цена со скидкой')),
                ('sortingIndex', models.IntegerField(blank=True, default=0, verbose_name='Индекс сортировки')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовать')], default='published', max_length=10)),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.navescategory')),
            ],
            options={
                'verbose_name': 'Навес',
                'verbose_name_plural': 'Навесы',
            },
        ),
    ]
