# Generated by Django 3.2.9 on 2022-03-15 10:53

import ckeditor_uploader.fields
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20220314_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name': 'Тип забора', 'verbose_name_plural': 'Типы заборов'},
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='Content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Короткое описание ', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='Image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='zabory/categories/%Y-%m-%d/'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='ShortDesc',
            field=models.TextField(blank=True, help_text='Короткое описание сервиса', max_length=165, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='Title',
            field=models.CharField(blank=True, help_text='Введите категорию услуги', max_length=100, null=True, verbose_name='Название тип забора'),
        ),
    ]
