# Generated by Django 3.2.9 on 2022-05-24 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20220315_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name': 'Тип забора', 'verbose_name_plural': 'Типы забора'},
        ),
    ]
