# Generated by Django 3.2.9 on 2022-05-25 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boarderdemontash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'Демонтаж старого забора',
                'verbose_name_plural': '[Boarder] Демонтаж старого забора',
            },
        ),
        migrations.CreateModel(
            name='BoarderdlinaZabora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Начало промежутка')),
                ('end', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Конец промежутка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
            ],
            options={
                'verbose_name': 'длину забора',
                'verbose_name_plural': '[Boarder] Длина забора',
            },
        ),
        migrations.CreateModel(
            name='BoarderkalitkaStandart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'Калитка Стандарт',
                'verbose_name_plural': '[Boarder] Калитка Стандарт',
            },
        ),
        migrations.CreateModel(
            name='BoarderkmMkad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Начало промежутка')),
                ('end', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Конец промежутка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
            ],
            options={
                'verbose_name': 'расстояние МКАД',
                'verbose_name_plural': '[Rabiza] Количество км от МКАД',
            },
        ),
        migrations.CreateModel(
            name='Boardermethodstand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'Покрытие столбов',
                'verbose_name_plural': '[Boarder] Покрытие столбов',
            },
        ),
        migrations.CreateModel(
            name='Boarderotkat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'Откатные (сдвижные) ворота',
                'verbose_name_plural': '[Boarder] Откатные (сдвижные) ворота',
            },
        ),
        migrations.CreateModel(
            name='Boarderpaneli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'Панели 3D (ячейка 200*55 мм)',
                'verbose_name_plural': '[Boarder] Панели 3D (ячейка 200*55 мм)',
            },
        ),
        migrations.CreateModel(
            name='Boarderraspashvorota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'Распашные ворота',
                'verbose_name_plural': '[Boarder] Распашные ворота',
            },
        ),
        migrations.CreateModel(
            name='Boarderrazmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'Размер столбов, мм',
                'verbose_name_plural': '[Boarder] Размер столбов, мм',
            },
        ),
        migrations.CreateModel(
            name='BoardervisotaZabora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'высоту забора',
                'verbose_name_plural': '[Boarder] Высота забора',
            },
        ),
        migrations.CreateModel(
            name='Metaldemontash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'Демонтаж старого забора',
                'verbose_name_plural': '[Metal] Демонтаж старого забора',
            },
        ),
        migrations.CreateModel(
            name='Metaldetektprotekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'Защитная декоративная планка',
                'verbose_name_plural': '[Metal] Защитная декоративная планка',
            },
        ),
        migrations.CreateModel(
            name='MetaldlinaZabora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Начало промежутка')),
                ('end', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Конец промежутка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
            ],
            options={
                'verbose_name': 'длину забора',
                'verbose_name_plural': '[Metal] Длина забора',
            },
        ),
        migrations.CreateModel(
            name='MetalkmMkad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Начало промежутка')),
                ('end', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Конец промежутка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
            ],
            options={
                'verbose_name': 'расстояние МКАД',
                'verbose_name_plural': '[Rabiza] Количество км от МКАД',
            },
        ),
        migrations.CreateModel(
            name='Metalkolvoryadlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'Количество рядов',
                'verbose_name_plural': '[Metal] Количество рядов',
            },
        ),
        migrations.CreateModel(
            name='Metalkreplenieshtaketnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'Крепление',
                'verbose_name_plural': '[Metal] Крепление',
            },
        ),
        migrations.CreateModel(
            name='Metalmetodystanovki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'Метод установки',
                'verbose_name_plural': '[Metal] Метод установки',
            },
        ),
        migrations.CreateModel(
            name='Metalotkat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'Откатные (сдвижные) ворота',
                'verbose_name_plural': '[Metal] Откатные (сдвижные) ворота',
            },
        ),
        migrations.CreateModel(
            name='Metalpaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'Покраска',
                'verbose_name_plural': '[Metal] Покраска',
            },
        ),
        migrations.CreateModel(
            name='Metalpokritiestaketnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'Покрытие',
                'verbose_name_plural': '[Metal] Покрытие',
            },
        ),
        migrations.CreateModel(
            name='Metalraspash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'Распашные ворота',
                'verbose_name_plural': '[Metal] Распашные ворота',
            },
        ),
        migrations.CreateModel(
            name='Metalrazmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'Размер и толщина столбцов',
                'verbose_name_plural': '[Metal] Размер и толщина столбцов',
            },
        ),
        migrations.CreateModel(
            name='Metalshag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'Шаг между столбами',
                'verbose_name_plural': '[Metal] Шаг между столбами',
            },
        ),
        migrations.CreateModel(
            name='Metalstandart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'Калитка Стандарт',
                'verbose_name_plural': '[Metal] Калитка Стандарт',
            },
        ),
        migrations.CreateModel(
            name='Metaltipshtaketnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'Штакетник',
                'verbose_name_plural': '[Metal] Штакетник',
            },
        ),
        migrations.CreateModel(
            name='MetalvisotaZabora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'высоту забора',
                'verbose_name_plural': '[Metal] Высота забора',
            },
        ),
        migrations.CreateModel(
            name='Metalzazor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'Зазор',
                'verbose_name_plural': '[Metal] Зазор',
            },
        ),
        migrations.CreateModel(
            name='NavesidlinaZabora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Начало промежутка')),
                ('end', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Конец промежутка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
            ],
            options={
                'verbose_name': 'длину забора',
                'verbose_name_plural': '[Navesi] Длина забора',
            },
        ),
        migrations.CreateModel(
            name='Navesifermi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'Боковые фермы',
                'verbose_name_plural': '[Navesi] Боковые фермы',
            },
        ),
        migrations.CreateModel(
            name='Navesikrovlya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'Кровельный материал',
                'verbose_name_plural': '[Navesi] Кровельный материал',
            },
        ),
        migrations.CreateModel(
            name='NavesiMetalkmMkad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Начало промежутка')),
                ('end', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Конец промежутка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
            ],
            options={
                'verbose_name': 'расстояние МКАД',
                'verbose_name_plural': '[Rabiza] Количество км от МКАД',
            },
        ),
        migrations.CreateModel(
            name='Navesimethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'Метод установки столбов',
                'verbose_name_plural': '[Navesi] Метод установки столбов',
            },
        ),
        migrations.CreateModel(
            name='Navesirazmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'Размер и толщина столбцо',
                'verbose_name_plural': '[Navesi] Размер и толщина столбцо',
            },
        ),
        migrations.CreateModel(
            name='NavesishirinaZabora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Начало промежутка')),
                ('end', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Конец промежутка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
            ],
            options={
                'verbose_name': 'Ширина забора',
                'verbose_name_plural': '[Navesi] Ширина забора',
            },
        ),
        migrations.CreateModel(
            name='Navesityp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'Тип фермы',
                'verbose_name_plural': '[Navesi] Тип фермы',
            },
        ),
        migrations.CreateModel(
            name='NavesivisotaZabora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'высоту забора',
                'verbose_name_plural': '[Navesi] Высота забора',
            },
        ),
        migrations.CreateModel(
            name='ProfnastilEdinicaIzmereniya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, help_text='Введите единица измерения', max_length=100, null=True, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': '[Profnastil] Единица измерении',
            },
        ),
        migrations.CreateModel(
            name='ProfnastilKraska',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, help_text='Введите названия покрытия', max_length=100, null=True, verbose_name='Название покрытия')),
                ('kolichestvo', models.DecimalField(blank=True, decimal_places=2, default=1.0, help_text='Количество', max_digits=10, null=True, verbose_name='Количество')),
                ('edIzmer', models.CharField(blank=True, choices=[('1', 'пм')], default='1', help_text='Выберите толшину покрытия', max_length=20, null=True, verbose_name='Единица Измерения')),
                ('cena', models.DecimalField(blank=True, decimal_places=2, default=400.0, help_text='Цена', max_digits=10, null=True, verbose_name='Цена единицы')),
            ],
            options={
                'verbose_name': 'Краска',
                'verbose_name_plural': '[Profnastil] Краски',
            },
        ),
        migrations.CreateModel(
            name='ProfnastilLaborCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workType', models.CharField(blank=True, choices=[('ustZaborProfnast', 'Установка забора из профнастиля'), ('drugoe', 'Другое')], default='drugoe', help_text='Выберите тип', max_length=20, null=True, verbose_name='Тип работы')),
                ('Title', models.CharField(blank=True, help_text='Введите названия работы', max_length=100, null=True, verbose_name='Название работы')),
                ('kolichestvo', models.DecimalField(blank=True, decimal_places=2, default=1.0, help_text='Количество', max_digits=10, null=True, verbose_name='Количество')),
                ('edIzmer', models.CharField(blank=True, choices=[('1', 'пм'), ('2', 'упак'), ('3', 'компл'), ('4', 'шт')], default='1', help_text='Выберите единицу', max_length=20, null=True, verbose_name='Единица Измерения')),
                ('param1', models.CharField(blank=True, help_text='Например, высоту: 1.5', max_length=10, null=True, verbose_name='Параметр 1')),
                ('param2', models.CharField(blank=True, help_text='Например, ширину: 2.5', max_length=10, null=True, verbose_name='Параметр 2')),
                ('param3', models.CharField(blank=True, help_text='Например, толшину: 0.30', max_length=10, null=True, verbose_name='Параметр 3')),
                ('cena', models.DecimalField(blank=True, decimal_places=2, default=400.0, help_text='Цена', max_digits=10, null=True, verbose_name='Цена единицы')),
                ('Slug', models.CharField(blank=True, help_text='Введите ссылку. Нельзя изменить! ', max_length=20, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Стоимость работы',
                'verbose_name_plural': '[Profnastil] Стоимость работы',
            },
        ),
        migrations.CreateModel(
            name='ProfnastilPokritie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, help_text='Введите названия покрытия', max_length=100, null=True, verbose_name='Название покрытия')),
                ('marka', models.CharField(blank=True, choices=[('1', 'C')], default='1', help_text='Выберите толшину покрытия', max_length=20, null=True, verbose_name='Марка')),
                ('kolVolna', models.CharField(blank=True, choices=[('1', '8'), ('2', '20'), ('3', '21')], default='1', help_text='Выберите количество волн', max_length=20, null=True, verbose_name='Кол. волны')),
                ('tolshina', models.CharField(blank=True, choices=[('1', '0.30'), ('2', '0.35'), ('3', '0.40'), ('4', '0.45'), ('5', '0.50')], default='1', help_text='Выберите толшину покрытия', max_length=20, null=True, verbose_name='Толшина')),
                ('kraska', models.CharField(blank=True, choices=[('1', 'односторонный'), ('2', 'двусторонный'), ('3', 'оцинкованный')], default='1', help_text='Выберите толшину покрытия', max_length=20, null=True, verbose_name='Краска')),
                ('kolichestvo', models.IntegerField(blank=True, default=1, help_text='Количество', null=True, verbose_name='Количество')),
                ('edIzmer', models.CharField(blank=True, choices=[('1', 'м2')], default='1', help_text='Выберите толшину покрытия', max_length=20, null=True, verbose_name='Единица Измерения')),
                ('cena', models.IntegerField(blank=True, default=0, help_text='Цена', null=True, verbose_name='Цена единицы')),
            ],
            options={
                'verbose_name': 'Тип покрытие',
                'verbose_name_plural': '[Profnastil] Тип покрытия',
            },
        ),
        migrations.CreateModel(
            name='ProfnastilSechenieStolba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, help_text='Введите сечение столбы', max_length=100, null=True, verbose_name='Сечение столбы')),
                ('edIzmereniya', models.CharField(blank=True, help_text='Введите единицу измерения', max_length=100, null=True, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Сечение столб',
                'verbose_name_plural': '[Profnastil] Сечение столбы',
            },
        ),
        migrations.CreateModel(
            name='ProfnastilServicesAndMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtip', models.CharField(blank=True, choices=[('beton', 'Бетонирование'), ('utrambovka', 'Утрамбовка'), ('gruntovka', 'Грунтовка'), ('lagi', 'Лаги'), ('zaglushka', 'Заглушка'), ('zamosrezi', 'Саморезы'), ('planka', 'Планка'), ('kalitka', 'Калитка'), ('vorota', 'Ворота'), ('rabota', 'Работа'), ('drugoe', 'Другое')], default='drugoe', help_text='Выберите тип', max_length=20, null=True, verbose_name='Тип услуги/материала')),
                ('Title', models.CharField(blank=True, help_text='Введите названия усгули или материала', max_length=100, null=True, verbose_name='Название усгули или материала')),
                ('kolichestvo', models.DecimalField(blank=True, decimal_places=2, default=1.0, help_text='Количество', max_digits=10, null=True, verbose_name='Количество')),
                ('edIzmer', models.CharField(blank=True, choices=[('1', 'пм'), ('2', 'упак'), ('3', 'компл'), ('4', 'шт')], default='1', help_text='Выберите единицу', max_length=20, null=True, verbose_name='Единица Измерения')),
                ('param1', models.CharField(blank=True, help_text='Например, высоту: 1.5', max_length=10, null=True, verbose_name='Параметр 1')),
                ('param2', models.CharField(blank=True, help_text='Например, ширину: 2.5', max_length=10, null=True, verbose_name='Параметр 2')),
                ('param3', models.CharField(blank=True, help_text='Например, толшину: 0.30', max_length=10, null=True, verbose_name='Параметр 3')),
                ('cena', models.DecimalField(blank=True, decimal_places=2, default=400.0, help_text='Цена', max_digits=10, null=True, verbose_name='Цена единицы')),
                ('Slug', models.CharField(blank=True, help_text='Введите ссылку. Нельзя изменить! ', max_length=20, null=True, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Другой  материал',
                'verbose_name_plural': '[Profnastil] Другие материалы',
            },
        ),
        migrations.CreateModel(
            name='ProfnastilTipStolba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, help_text='Введите тип столбы', max_length=100, null=True, verbose_name='Тип/Наименование столбы')),
            ],
            options={
                'verbose_name': 'Тип столб',
                'verbose_name_plural': '[Profnastil] Тип столба',
            },
        ),
        migrations.CreateModel(
            name='ProfnastilTolshinaStolba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, help_text='Введите толшина столбы', max_length=100, null=True, verbose_name='Толшина столбы')),
                ('edIzmereniya', models.CharField(blank=True, help_text='Введите единицу измерения толшина столбы', max_length=100, null=True, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Толшина столб',
                'verbose_name_plural': '[Profnastil] Толшина столбы',
            },
        ),
        migrations.CreateModel(
            name='Rabizademontashvorot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'демонтаж старого забора:',
                'verbose_name_plural': '[Rabiza] Демонтаж старого забора:',
            },
        ),
        migrations.CreateModel(
            name='Rabizadlinazabora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Начало промежутка')),
                ('end', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Конец промежутка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
            ],
            options={
                'verbose_name': 'длину забора',
                'verbose_name_plural': '[Rabiza] Длина забора',
            },
        ),
        migrations.CreateModel(
            name='Rabizakalitkastandart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'Калитка "Стандарт"',
                'verbose_name_plural': '[Rabiza] Калитка "Стандарт"',
            },
        ),
        migrations.CreateModel(
            name='Rabizakmmkad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Начало промежутка')),
                ('end', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Конец промежутка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
            ],
            options={
                'verbose_name': 'расстояние МКАД',
                'verbose_name_plural': '[Rabiza] Количество км от МКАД',
            },
        ),
        migrations.CreateModel(
            name='Rabizamethodystanovkistolbov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'метод установки столбов',
                'verbose_name_plural': '[Rabiza] Метод установки столбов',
            },
        ),
        migrations.CreateModel(
            name='Rabizapokraskastolb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'покраску столбов и секций',
                'verbose_name_plural': '[Rabiza] Покраска столбов и секций',
            },
        ),
        migrations.CreateModel(
            name='Rabizaraspashnievorota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'распашные ворота:',
                'verbose_name_plural': '[Rabiza] Распашные ворота:',
            },
        ),
        migrations.CreateModel(
            name='Rabizarazmertolshinastolb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'размер и толщину столбов',
                'verbose_name_plural': '[Rabiza] Размер и толщина столбов',
            },
        ),
        migrations.CreateModel(
            name='Rabizashirinavorot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'ширину ворот',
                'verbose_name_plural': '[Rabiza] Ширина ворот',
            },
        ),
        migrations.CreateModel(
            name='Rabizavisotazabora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение поля')),
                ('mnosh', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Умножить результат при выборе на')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Прибавлять за каждый каждый метр')),
            ],
            options={
                'verbose_name': 'высоту забора',
                'verbose_name_plural': '[Rabiza] Высота забора',
            },
        ),
        migrations.CreateModel(
            name='ProfnastilStolba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolichestvo', models.IntegerField(blank=True, default=0, help_text='Количество', null=True, verbose_name='Количество')),
                ('cena', models.IntegerField(blank=True, default=0, help_text='Цена', null=True, verbose_name='Цена единицы')),
                ('edinicaIzmereniya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculator.profnastiledinicaizmereniya')),
                ('sechenieStolba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculator.profnastilsecheniestolba')),
                ('tipStolba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculator.profnastiltipstolba')),
                ('tolshinaStolba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculator.profnastiltolshinastolba')),
            ],
            options={
                'verbose_name': 'Столба',
                'verbose_name_plural': '[Profnastil] Столбы',
            },
        ),
    ]
