# Generated by Django 3.2.9 on 2022-06-06 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metallags',
            options={'verbose_name': '[Metal] Лаги', 'verbose_name_plural': '[Metal] Лаги'},
        ),
    ]
