# Generated by Django 3.2.9 on 2022-06-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metaldlinastolbov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visota', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Высота столба')),
                ('tolshina', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Толщина столба')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Цена конфигурации')),
            ],
            options={
                'verbose_name': '[Metal] Цена столбов',
                'verbose_name_plural': '[Metal] Цена столбов',
            },
        ),
        migrations.CreateModel(
            name='Metalkalitka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visota', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Высота')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Цена')),
            ],
            options={
                'verbose_name': '[Metal] Калитка',
                'verbose_name_plural': '[Metal] Калитка',
            },
        ),
        migrations.CreateModel(
            name='Metalpokraska',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=100, verbose_name='Тип краски')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Цена')),
                ('kolvo', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Количество краски на метр')),
            ],
            options={
                'verbose_name': '[Metal] Покраска',
                'verbose_name_plural': '[Metal] Покраска',
            },
        ),
        migrations.CreateModel(
            name='Metalvorota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visota', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Высота')),
                ('shirina', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Ширина')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Цена')),
            ],
            options={
                'verbose_name': '[Metal] Ворота',
                'verbose_name_plural': '[Metal] Ворота',
            },
        ),
        migrations.CreateModel(
            name='Metalystanovkakalitki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Цена')),
            ],
            options={
                'verbose_name': '[Metal] Установка калитки',
                'verbose_name_plural': '[Metal] Установка калитки',
            },
        ),
        migrations.CreateModel(
            name='Metalystanovkavorot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Цена за установку ворот')),
            ],
            options={
                'verbose_name': '[Metal] Цена за установку ворот',
                'verbose_name_plural': '[Metal] Цена за установку ворот',
            },
        ),
        migrations.CreateModel(
            name='Metalystanovkazabora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Начало промежутка')),
                ('end', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Конец промежутка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Цена за установку забора')),
            ],
            options={
                'verbose_name': '[Metal] Цена за установку забора',
                'verbose_name_plural': '[Metal] Цена за установку забора',
            },
        ),
    ]
