# Generated by Django 3.2.9 on 2022-06-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profnastildlinastolbov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visota', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Высота столба')),
                ('tolshina', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Толщина столба')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Цена конфигурации')),
            ],
            options={
                'verbose_name': '[Profnastil] Цена столбов',
                'verbose_name_plural': '[Profnastil] Цена столбов',
            },
        ),
        migrations.CreateModel(
            name='Profnastilkalitka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visota', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Высота')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Цена')),
            ],
            options={
                'verbose_name': '[Profnastil] Калитка',
                'verbose_name_plural': '[Profnastil] Калитка',
            },
        ),
        migrations.CreateModel(
            name='Profnastillags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Количество горизонталей (лаги)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Цена конфигурации')),
                ('count_mnsh', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Множитель количества')),
            ],
            options={
                'verbose_name': '[Profnastil] Лаги',
                'verbose_name_plural': '[Profnastil] Лаги',
            },
        ),
        migrations.CreateModel(
            name='Profnastilpokraska',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=100, verbose_name='Тип краски')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Цена')),
                ('kolvo', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Количество краски на метр')),
            ],
            options={
                'verbose_name': '[Profnastil] Покраска',
                'verbose_name_plural': '[Profnastil] Покраска',
            },
        ),
        migrations.CreateModel(
            name='Profnastilshtaketnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название штакетника')),
                ('polymer', models.CharField(max_length=100, verbose_name='Название полимера')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Цена конфигурации')),
            ],
            options={
                'verbose_name': '[Profnastil] Штакетник',
                'verbose_name_plural': '[Profnastil] Штакетник',
            },
        ),
        migrations.CreateModel(
            name='Profnastilvorota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visota', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Высота')),
                ('shirina', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Ширина')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Цена')),
            ],
            options={
                'verbose_name': '[Profnastil] Ворота',
                'verbose_name_plural': '[Profnastil] Ворота',
            },
        ),
        migrations.CreateModel(
            name='Profnastilystanovkakalitki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Цена')),
            ],
            options={
                'verbose_name': '[Profnastil] Установка калитки',
                'verbose_name_plural': '[Profnastil] Установка калитки',
            },
        ),
        migrations.CreateModel(
            name='Profnastilystanovkavorot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Цена за установку ворот')),
            ],
            options={
                'verbose_name': '[Profnastil] Цена за установку ворот',
                'verbose_name_plural': '[Profnastil] Цена за установку ворот',
            },
        ),
        migrations.CreateModel(
            name='Profnastilystanovkazabora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Начало промежутка')),
                ('end', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Конец промежутка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Цена за установку забора')),
            ],
            options={
                'verbose_name': '[Profnastil] Цена за установку забора',
                'verbose_name_plural': '[Profnastil] Цена за установку забора',
            },
        ),
        migrations.DeleteModel(
            name='ProfnastilKraska',
        ),
        migrations.DeleteModel(
            name='ProfnastilLaborCost',
        ),
        migrations.DeleteModel(
            name='ProfnastilPokritie',
        ),
        migrations.DeleteModel(
            name='ProfnastilServicesAndMaterials',
        ),
        migrations.RemoveField(
            model_name='profnastilstolba',
            name='edinicaIzmereniya',
        ),
        migrations.RemoveField(
            model_name='profnastilstolba',
            name='sechenieStolba',
        ),
        migrations.RemoveField(
            model_name='profnastilstolba',
            name='tipStolba',
        ),
        migrations.RemoveField(
            model_name='profnastilstolba',
            name='tolshinaStolba',
        ),
        migrations.DeleteModel(
            name='ProfnastilEdinicaIzmereniya',
        ),
        migrations.DeleteModel(
            name='ProfnastilSechenieStolba',
        ),
        migrations.DeleteModel(
            name='ProfnastilStolba',
        ),
        migrations.DeleteModel(
            name='ProfnastilTipStolba',
        ),
        migrations.DeleteModel(
            name='ProfnastilTolshinaStolba',
        ),
    ]
