# Generated by Django 3.2.9 on 2022-06-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_metaldlinastolbov_metalkalitka_metalpokraska_metalvorota_metalystanovkakalitki_metalystanovkavorot_m'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boarderdlinastolbov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visota', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Высота столба')),
                ('tolshina', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Толщина столба')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Цена конфигурации')),
            ],
            options={
                'verbose_name': '[Boarder] Цена столбов',
                'verbose_name_plural': '[Boarder] Цена столбов',
            },
        ),
        migrations.CreateModel(
            name='Boarderkalitka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visota', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Высота')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Цена')),
            ],
            options={
                'verbose_name': '[Boarder] Калитка',
                'verbose_name_plural': '[Boarder] Калитка',
            },
        ),
        migrations.CreateModel(
            name='Boarderpokraska',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=100, verbose_name='Тип краски')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Цена')),
                ('kolvo', models.DecimalField(decimal_places=5, max_digits=100, verbose_name='Количество краски на метр')),
            ],
            options={
                'verbose_name': '[Boarder] Покраска',
                'verbose_name_plural': '[Boarder] Покраска',
            },
        ),
        migrations.CreateModel(
            name='Boardervorota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visota', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Высота')),
                ('shirina', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Ширина')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Цена')),
            ],
            options={
                'verbose_name': '[Boarder] Ворота',
                'verbose_name_plural': '[Boarder] Ворота',
            },
        ),
        migrations.CreateModel(
            name='Boarderystanovkakalitki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Цена')),
            ],
            options={
                'verbose_name': '[Boarder] Установка калитки',
                'verbose_name_plural': '[Boarder] Установка калитки',
            },
        ),
        migrations.CreateModel(
            name='Boarderystanovkavorot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Цена за установку ворот')),
            ],
            options={
                'verbose_name': '[Boarder] Цена за установку ворот',
                'verbose_name_plural': '[Boarder] Цена за установку ворот',
            },
        ),
        migrations.CreateModel(
            name='Boarderystanovkazabora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Начало промежутка')),
                ('end', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Конец промежутка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Цена за установку забора')),
            ],
            options={
                'verbose_name': '[Boarder] Цена за установку забора',
                'verbose_name_plural': '[Boarder] Цена за установку забора',
            },
        ),
    ]
