# Generated by Django 3.2.9 on 2022-06-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_metallags_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metalshtaketnik',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Количество горизонталей (лаги)'),
        ),
    ]
