# Generated by Django 3.2.9 on 2022-06-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_boarderdlinastolbov_boarderkalitka_boarderpokraska_boardervorota_boarderystanovkakalitki_boarderysta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boarder3d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visota', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Цена конфигурации')),
            ],
            options={
                'verbose_name': '[Boarder] 3d панели',
                'verbose_name_plural': '[Boarder] 3d панели',
            },
        ),
    ]
