# Generated by Django 3.2.9 on 2022-06-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_alter_metalshtaketnik_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metallags',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Количество горизонталей (лаги)'),
        ),
        migrations.AlterField(
            model_name='metalshtaketnik',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название штакетника'),
        ),
    ]
